### ISSUE TITLE
Migrate to non-blockable sockets

### ISSUE THREAD

**Issue by AntonyMoes** [AntonyMoes/VPN#1]

**Comment by indiagolph99** [comment]
Чекай веточку. Еще не всё идеально. Но ответ близок, я чувствую. Можешь сам посмотреть, нужна пара свежих глаз. Там не так уж всё и сложно

**Comment by AntonyMoes** [comment]
@indiagolph99 а где ожидаема проблема? В cli_connect и ser_connect? Или в main'е?
